# Generated by Django 4.1 on 2023-02-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thc', '0002_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplanUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Activity Name')),
                ('responsible', models.CharField(blank=True, max_length=300, null=True, verbose_name='Responsible')),
                ('implimentation', models.URLField(blank=True, max_length=300, null=True, verbose_name='website link')),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='headquater',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Headquater'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Organization Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='website link'),
        ),
    ]
